### ISSUE TITLE
LegalfactIds on ProgressResponseElement of streams

### ISSUE THREAD

**Issue by MassimoLuise** [pagopa/pn-local-emulator#134]
Dalla documentazione di "/delivery-progresses/streams/{streamId}/events", l'attributo "legalfactIds" dovrebbe contenere un array di stringhe del tipo 

example: List [ "PN_LEGAL_FACTS-0002-9G2S-RK3M-JI62-JK9Q", "PN_LEGAL_FACTS-0002-9G2S-RK3M-JI62-JK9E" ]
chiavi degli eventuali allegati associati all'evento

Quello che si ha con la versione 0.14.2 è invece un array di stringhe con la categoria del legalfact.

Credo dipenda da questa riga in **src/domain/ConsumeEventStreamRecord.ts**

**legalfactIds: legalFactsIds?.map(({ category }) => category),**

secondo me dovrebbe essere riscritta in 

**legalfactIds: legalFactsIds?.map(({ key }) => key),**

Questo porta ad avere problemi con il download dei legalfacts

**Comment by dennycarusonttdata** [comment]
Problematica risolta con il rilascio della versione 0.14.10. Grazie della segnalazione.
